language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
install:
  - composer install
  - composer global require "codeception/codeception:*"
  - alias codecept='/home/travis/.composer/vendor/bin/codecept'

script:
  - /home/travis/.composer/vendor/bin/codecept run